language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm i
  - ls -la
  - npm run build
deploy:
  provider: surge
  project: ./public/
  skip_cleanup: true
  domain: tricky-anger.surge.sh
  on:
    branch: develop